/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPriceOracleV1,
  IPriceOracleV1Interface,
} from "../../../../contracts/oracle/price/IPriceOracleV1";

const _abi = [
  {
    inputs: [],
    name: "price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPriceOracleV1__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceOracleV1Interface {
    return new utils.Interface(_abi) as IPriceOracleV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceOracleV1 {
    return new Contract(address, _abi, signerOrProvider) as IPriceOracleV1;
  }
}
