/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockChainlinkDataFeed } from "./MockChainlinkDataFeed";
export type { TestErc20 } from "./TestErc20";
export type { TestReceipt } from "./TestReceipt";
export type { TestReceiptOwner } from "./TestReceiptOwner";
