/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReceiptOwnerV1,
  IReceiptOwnerV1Interface,
} from "../../../../contracts/vault/receipt/IReceiptOwnerV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "authorizeReceiptTransfer",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IReceiptOwnerV1__factory {
  static readonly abi = _abi;
  static createInterface(): IReceiptOwnerV1Interface {
    return new utils.Interface(_abi) as IReceiptOwnerV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReceiptOwnerV1 {
    return new Contract(address, _abi, signerOrProvider) as IReceiptOwnerV1;
  }
}
