name: flow-subgraph-test
on: [push, pull_request]

env:
  GRAPH_TOKEN: ${{ secrets.GRAPH_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Docker
        run: |
          # Install dependencies for Docker installation
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

          # Add Docker’s official GPG key
          echo "deb [arch=$(dpkg --print-architecture) ] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          
          # Update the package database and install Docker
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Docker Compose images
        run: |
          docker-compose down
          docker-compose up --build -d

      - name: Run Subgraph tests
        run: |
          npm run ci-test

      - name: Stop containers
        run: docker-compose down
